import type { POI } from "./types";

/**
 * 가볼 만한 곳 — 양양 · 강릉 · 평창.
 *
 * 자차 여행 기준으로 parking · admission · openHours · crowdLevel 을 최대한 채웠다.
 * 8월 해수욕장 개장 기간을 검색으로 확인해 반영했다 (여행 기간 8/14~17 기준).
 * verification 은 "needs-check" — 확인 못 한 필드는 생략했다.
 */
export const pois: POI[] = [
  // ── 양양 ─────────────────────────────────────
  {
    emoji: "🏄",
    name: "죽도해변",
    category: "해변 · 서핑",
    area: "양양",
    description: "서핑 숍 30여 개가 모인 서핑의 메카. 해변 앞 거리는 '양리단길'로 불리는 핫플레이스.",
    why: "서핑을 안 타도 구경만으로 즐길거리가 많고, 카페 · 펍이 밀집해 있음",
    address: "강원 양양군 현남면 죽도해변길 (죽도해변)",
    place: { lat: 37.9756, lng: 128.7596 },
    visitTime: "1~2시간",
    openHours: "상시 개방",
    admission: "무료",
    parking: { available: true, fee: "무료 (인근 공영주차장)", note: "8월 성수기 주말은 만차 가능" },
    crowdLevel: "high",
    companionNote: "아이 동반 시 파도 · 서핑보드 동선 주의",
    verification: "needs-check",
  },
  {
    emoji: "🏖️",
    name: "낙산해수욕장",
    category: "해변",
    area: "양양",
    description: "1963년 개장한 양양 대표 해변. 2026년 처음으로 야간 개장(밤 9시까지)을 운영.",
    why: "8/14~16 야간 개장 기간과 이번 여행 일정이 정확히 겹침",
    address: "강원 양양군 강현면 낙산해변길 (낙산해수욕장)",
    place: { lat: 38.1156, lng: 128.6360 },
    visitTime: "1~3시간",
    openHours: "2026년 개장 7/10~8/23, 수영 가능 09:00~18:00 (8/14~16 야간 개장 시 21:00까지)",
    admission: "무료",
    parking: { available: true, note: "공영주차장 있음, 요금 확인 필요" },
    crowdLevel: "high",
    companionNote: "8/15 광복절과 겹쳐 매우 혼잡할 수 있음",
    verification: "needs-check",
  },
  {
    emoji: "⛩️",
    name: "낙산사",
    category: "사찰 · 전망",
    area: "양양",
    description: "671년 의상대사가 창건한 관동팔경 중 하나. 해수관음상과 절벽 위 홍련암이 유명.",
    why: "동해 전망이 아름답고 2023년부터 입장료가 전면 무료화됨",
    address: "강원 양양군 강현면 낙산사로 100",
    place: { lat: 38.1245, lng: 128.6291 },
    visitTime: "1~2시간",
    openHours: "하계(여름) 06:00~19:30 (입장마감 17:00)",
    admission: "무료 (2023년 문화재관람료 전면 폐지)",
    parking: { available: true, fee: "정문 5,000원 · 의상대 4,000원 · 낙산항 무료" },
    crowdLevel: "mid",
    companionNote: "반려동물 동반 입장 불가",
    verification: "needs-check",
  },
  {
    emoji: "🌊",
    name: "하조대",
    category: "전망 · 정자",
    area: "양양",
    description: "기암절벽과 소나무, 등대가 어우러진 동해 전망 명소.",
    why: "24시간 무료 개방이라 일정에 유연하게 끼워 넣기 좋음",
    address: "강원 양양군 현북면 하조대길 (하조대)",
    place: { lat: 38.0201, lng: 128.7235 },
    visitTime: "30분~1시간",
    openHours: "24시간 개방",
    admission: "무료",
    parking: { available: true, fee: "무료" },
    crowdLevel: "low",
    verification: "needs-check",
  },

  // ── 강릉 ─────────────────────────────────────
  {
    emoji: "☕",
    name: "안목해변 커피거리",
    category: "해변 · 카페거리",
    area: "강릉",
    description: "박이추 · 김용덕 등 커피 1세대가 자리 잡으며 형성된 전국구 커피거리. 해변 바로 앞.",
    why: "커피와 바다 전망을 함께 즐길 수 있는 강릉 대표 코스",
    address: "강원 강릉시 창해로14번길 일대",
    place: { lat: 37.7728, lng: 128.9476 },
    visitTime: "1~2시간",
    openHours: "카페별 상이",
    admission: "무료",
    parking: { available: true, note: "해변 공영주차장, 성수기 혼잡 · 요금 확인 필요" },
    crowdLevel: "high",
    verification: "needs-check",
  },
  {
    emoji: "🏖️",
    name: "경포해수욕장",
    category: "해변",
    area: "강릉",
    description: "강원 동해안을 대표하는 해변. 경포호 · 경포대와 인접.",
    why: "백사장이 넓고 편의시설이 잘 갖춰져 있어 가족 단위로 방문하기 좋음",
    address: "강원 강릉시 경포동 (경포해수욕장)",
    place: { lat: 37.8038, lng: 128.9099 },
    visitTime: "1~3시간",
    openHours: "2026년 개장 7/4~8/23 (51일간), 수영 가능 09:00~18:00",
    admission: "무료",
    parking: { available: true, note: "공영주차장 있음, 요금 확인 필요" },
    crowdLevel: "high",
    companionNote: "8/15 광복절과 겹쳐 매우 혼잡할 수 있음",
    verification: "needs-check",
  },
  {
    emoji: "🏯",
    name: "오죽헌",
    category: "고택 · 박물관",
    area: "강릉",
    description: "신사임당과 율곡 이이가 태어난 조선 시대 가옥. 시립박물관이 함께 있음.",
    why: "역사 · 문화 체험과 실내 관람이 가능해 더위 · 우천 대비용으로도 좋음",
    address: "강원 강릉시 율곡로3139번길 24",
    place: { lat: 37.7786, lng: 128.8778 },
    visitTime: "1~1.5시간",
    openHours: "09:00~18:00 (입장마감 17:00), 연중무휴",
    admission: "성인 3,000원 · 청소년 2,000원 · 어린이 1,000원 (65세 이상 무료)",
    parking: { available: true, fee: "무료", note: "만차 시 인근 강릉농악전수관 주차장 이용" },
    crowdLevel: "mid",
    verification: "needs-check",
  },
  {
    emoji: "🌄",
    name: "안반데기",
    category: "고원 전망",
    area: "강릉",
    description: "해발 1,100m 고랭지 배추밭 고원. 일출 · 별빛 명소로 유명.",
    why: "여름철 시원한 고원 공기와 탁 트인 전망, 평창 숙소에서 접근성도 좋음",
    address: "강원 강릉시 왕산면 안반데기길",
    place: { lat: 37.6228, lng: 128.7504 },
    visitTime: "1~2시간",
    openHours: "상시 개방",
    admission: "무료",
    parking: { available: true, fee: "무료", note: "주말 · 성수기 새벽에는 혼잡할 수 있음" },
    crowdLevel: "mid",
    verification: "needs-check",
  },

  // ── 평창 ─────────────────────────────────────
  {
    emoji: "🐑",
    name: "대관령 양떼목장",
    category: "목장 · 체험",
    area: "평창",
    description: "해발 850m 고지에 양떼가 뛰노는 초원 목장. 5회 연속 한국관광 100선 선정.",
    why: "여름철 고원의 시원함과 동물 체험을 동시에 즐길 수 있음",
    address: "강원 평창군 대관령면 대관령마루길 483-32",
    place: { lat: 37.6868, lng: 128.7528 },
    visitTime: "1~1.5시간",
    openHours: "5~8월 09:00~18:30 (매표마감 17:30)",
    admission: "대인 9,000원 · 소인 7,000원 · 우대 6,000원 (36개월 미만 무료)",
    parking: { available: true, fee: "무료 (약 200대)" },
    crowdLevel: "mid",
    companionNote: "먹이주기 체험 1,000원 별도, 언덕길이 있어 유아차는 다소 불편할 수 있음",
    verification: "needs-check",
  },
  {
    emoji: "🛕",
    name: "월정사",
    category: "사찰 · 숲길",
    area: "평창",
    description: "오대산 국립공원 내 천년 고찰. 전나무 숲길 산책로가 유명.",
    why: "서림원에서 가깝고, 울창한 숲길이라 여름에도 시원하게 걷기 좋음",
    address: "강원 평창군 진부면 오대산로 374-8",
    place: { lat: 37.7319, lng: 128.5920 },
    visitTime: "1~2시간",
    openHours: "일출 2시간 전 ~ 일몰 전",
    admission: "무료 (2023년 문화재관람료 전면 폐지)",
    parking: { available: true, note: "주차료 별도 부과 (금액은 출처마다 2,000~5,000원으로 상이, 현장 확인 필요)" },
    crowdLevel: "mid",
    companionNote: "전나무숲길은 평탄해 유모차 이동 가능",
    verification: "needs-check",
  },
  {
    emoji: "📖",
    name: "이효석문학관 · 효석문화마을",
    category: "문학관 · 마을",
    area: "평창",
    description: "소설 '메밀꽃 필 무렵'의 작가 이효석의 생가와 문학관이 있는 봉평 문학 마을.",
    why: "메밀밭 산책과 함께 평창 봉평 지역의 문화를 체험할 수 있음",
    address: "강원 평창군 봉평면 효석문학길 73-25",
    place: { lat: 37.6108, lng: 128.3651 },
    visitTime: "1~1.5시간",
    openHours: "성수기(5~9월) 09:00~18:30, 매주 월요일 휴관",
    admission: "성인 2,000원 · 중고생 1,500원 · 초등생 1,000원",
    parking: { available: true, fee: "무료" },
    crowdLevel: "low",
    verification: "needs-check",
  },
];
