import type { Restaurant } from "./types";

/**
 * 맛집 데이터 — 양양 · 강릉 · 평창.
 *
 * 블루리본 서베이 등재가 확인된 곳 위주로 선정했다 (근거 없는 곳은 제외).
 * verification 은 전부 "needs-check" — 방문 전 최신 영업시간 · 휴무일을 반드시 확인할 것.
 *
 * 감사 노트: "오삼불고기"(진부면, id: osam-bulgogi) 항목은 지어낸 데이터로 강하게
 * 의심되어(주소·전화번호가 다른 식당 것으로 확인됨) 삭제했다. 평창은 3곳 → 2곳.
 * 대체 후보(횡계 오삼불고기거리)는 WebSearch 로도 특정 업체를 독립 검증하지 못해 넣지 않았다.
 */
export const restaurants: Restaurant[] = [
  // ── 강릉 ─────────────────────────────────────
  {
    id: "chodang-halmoni-sundubu",
    name: "초당할머니순두부",
    category: "순두부",
    area: "강릉",
    signature: ["순두부전골", "모두부"],
    address: "강원 강릉시 초당순두부길 77",
    place: { lat: 37.7878, lng: 128.9110 },
    hours:
      "8월(성수기) 08:00~15:30 · 17:00~18:30 (브레이크 15:30~17:00) — 여행일(8/14~17)은 이 시간대 적용. 평소엔 평일 08:00~16:00·17:00~19:00, 화 08:00~15:00",
    openHours: { open: "08:00", close: "18:30", breakStart: "15:30", breakEnd: "17:00" },
    closedDays: "확인 필요 (8월 성수기 시간표에는 정기휴무 언급 없음, 방문 전 확인 권장)",
    priceRange: "1만원대",
    credentials: { awards: ["블루리본 서베이 등재"] },
    verification: "needs-check",
    mealTime: ["아침", "점심", "저녁"],
    phone: "033-652-2058",
    note: "초당순두부마을 중심에 위치. 방송 다수 소개, 대기 웨이팅 있음",
  },
  {
    id: "donghwa-garden",
    name: "동화가든 (원조 짬뽕순두부)",
    category: "순두부 · 짬뽕순두부",
    area: "강릉",
    signature: ["짬뽕순두부", "청국장"],
    address: "강원 강릉시 초당순두부길77번길 15",
    place: { lat: 37.7878, lng: 128.9110 },
    hours: "매일 07:00~19:30 (브레이크타임 16:00~17:00)",
    openHours: { open: "07:00", close: "19:30", breakStart: "16:00", breakEnd: "17:00" },
    closedDays: "수요일",
    closedWeekdays: [3],
    priceRange: "1만원대",
    credentials: { awards: ["블루리본 서베이 13년 연속 선정"] },
    verification: "needs-check",
    mealTime: ["아침", "점심", "저녁"],
    phone: "033-652-9885",
    note: "짬뽕순두부를 국내 최초로 만든 원조집. 매장 뒤 공영주차장 무료 이용 가능",
  },
  {
    id: "bohemian-coffee",
    name: "보헤미안 박이추커피 본점",
    category: "카페 · 핸드드립커피",
    area: "강릉",
    signature: ["핸드드립 커피"],
    address: "강원 강릉시 사천면 해안로 1107",
    place: { lat: 37.8509, lng: 128.8611 },
    hours: "목·금 09:00~17:00, 토·일 08:00~17:00 (월·화·수 휴무)",
    openHours: { open: "09:00", close: "17:00" },
    closedDays: "월 · 화 · 수",
    closedWeekdays: [1, 2, 3],
    priceRange: "1만원 미만",
    credentials: { awards: ["2025 블루리본 서베이 선정"] },
    verification: "needs-check",
    mealTime: ["카페"],
    phone: "033-642-6688",
    note: "커피 1세대 바리스타 박이추가 운영. 강릉 커피 문화의 시초 격인 곳",
  },
  {
    id: "crema-costa-gangneung",
    name: "크레마코스타 강릉본점",
    category: "카페 · 스페셜티커피",
    area: "강릉",
    signature: ["핸드드립 커피", "푸딩"],
    address: "강원 강릉시 대송길 46",
    place: { lat: 37.7863, lng: 128.8455 },
    hours:
      "17:00 마감 가능성 유력 — 저녁 방문 전 전화 확인 필수 (출처별 상이: 매일 11:30~17:00 / 주중 12:00~17:00 / 매일 10:00~21:00)",
    closedDays: "확인 필요",
    priceRange: "1만원 미만",
    credentials: { awards: ["블루리본 서베이 등재"] },
    verification: "needs-check",
    mealTime: ["카페"],
    phone: "033-648-0333",
    note: "반려동물 동반 가능, 전용 주차공간 있음",
  },

  // ── 양양 ─────────────────────────────────────
  {
    id: "haechon",
    name: "해촌",
    category: "섭국 · 해산물",
    area: "양양",
    signature: ["자연산 섭국"],
    address: "강원 양양군 손양면 동명로 81",
    place: { lat: 38.0822, lng: 128.6420 },
    hours: "07:00~15:30 (라스트오더 15:00), 수요일 휴무",
    openHours: { open: "07:00", close: "15:00" },
    closedDays: "수요일",
    closedWeekdays: [3],
    priceRange: "2만원대",
    credentials: { awards: ["블루리본 서베이 선정 (수요미식회 소개)"] },
    verification: "needs-check",
    mealTime: ["아침", "점심"],
    phone: "033-673-5050",
    note: "생물(자연산 섭) 소진 시 예고 없이 조기 마감·임시휴업할 수 있음. 방문 당일 전화 확인 권장",
  },
  {
    id: "songigol",
    name: "송이골",
    category: "송이버섯 요리",
    area: "양양",
    signature: ["자연송이돌솥밥", "송이전골"],
    address: "강원 양양군 손양면 동명로 4",
    place: { lat: 38.0822, lng: 128.6420 },
    hours: "09:00~20:00 (브레이크타임 14:00~17:00, 라스트오더 19:30), 화요일 휴무",
    openHours: { open: "09:00", close: "20:00", breakStart: "14:00", breakEnd: "17:00" },
    closedDays: "화요일 (5번째 화요일은 정상영업)",
    closedWeekdays: [2],
    priceRange: "2만원대~",
    credentials: { awards: ["2024 블루리본 서베이 선정"] },
    verification: "needs-check",
    mealTime: ["점심", "저녁"],
    phone: "0507-1309-8040",
    note: "2012년부터 이어온 양양 송이돌솥밥 원조",
  },
  {
    id: "yeonggwangjeong-memil",
    name: "영광정메밀국수",
    category: "메밀국수 · 막국수",
    area: "양양",
    signature: ["동치미막국수", "수육"],
    address: "강원 양양군 강현면 진미로 446",
    place: { lat: 38.1278, lng: 128.5837 },
    hours: "매일 10:00~19:00",
    openHours: { open: "10:00", close: "19:00" },
    closedDays: "확인 필요",
    priceRange: "1만원대",
    credentials: { awards: ["블루리본 서베이 리본 2개"] },
    verification: "needs-check",
    mealTime: ["점심", "저녁"],
    phone: "033-673-5254",
    note: "1974년부터 3대째 운영, 함흥식 동치미막국수 원조. 한옥 건물",
  },

  // ── 평창 ─────────────────────────────────────
  {
    id: "yucheon-makguksu",
    name: "유천막국수 본점",
    category: "메밀막국수",
    area: "평창",
    signature: ["물막국수", "비빔막국수", "메밀전병"],
    address: "강원 평창군 대관령면 만과봉길 58",
    place: { lat: 37.6657, lng: 128.6285 },
    hours: "매일 10:30~19:30 (라스트오더 19:00), 연중무휴",
    openHours: { open: "10:30", close: "19:30" },
    closedDays: "없음",
    priceRange: "1만원대",
    credentials: { awards: ["블루리본 서베이 2014년부터 연속 등재"] },
    verification: "needs-check",
    mealTime: ["점심", "저녁"],
    phone: "033-332-6423",
    note: "30년 넘게 변함없는 맛으로 알려진 대관령 대표 막국수집",
  },
  {
    id: "memilkkot-pilmuryeop",
    name: "메밀꽃필무렵",
    category: "메밀요리",
    area: "평창",
    signature: ["메밀막국수", "감자만두"],
    address: "강원 평창군 봉평면 이효석길 157",
    place: { lat: 37.6108, lng: 128.3651 },
    hours: "영업시간 확인 필요",
    closedDays: "확인 필요",
    priceRange: "1만원대",
    credentials: { awards: ["블루리본 서베이 등재 (효석문화마을 1호 식당)"] },
    verification: "needs-check",
    mealTime: ["점심", "저녁"],
    phone: "033-335-2323",
    note: "이효석문학관 바로 앞. 직접 재배한 메밀 사용",
  },
];
